//
//  FinalPresenter.swift
//  quizzie
//
//  Created Ensar Baba on 2.05.2020.
//  Copyright © 2020 Ensar Baba. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol FinalViewProtocol: class {
    func setRecord(record: Int)
}

// MARK: Presenter -
protocol FinalPresenterProtocol: class {
    var view: FinalViewProtocol? { get set }
    func fetchRecord()
}

class FinalPresenter: FinalPresenterProtocol {
    
    weak var view: FinalViewProtocol?
    public var quizStatus = QuizStatusData()
    
    init(view: FinalViewProtocol, quizStatus: QuizStatusData) {
        self.view = view
        self.quizStatus = quizStatus
    }
    
    func fetchRecord() {
        view?.setRecord(record: quizStatus.userPoint)
    }
}
