//
//  FinalViewController.swift
//  quizzie
//
//  Created Ensar Baba on 2.05.2020.
//  Copyright © 2020 Ensar Baba. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class FinalViewController: UIViewController {
    
    var presenter: FinalPresenterProtocol!
    
    lazy var recordTitleLabel: UILabel = {
        let label = UILabel()
        label.text = "Your Record"
        label.textAlignment = .center
        label.textColor = .black
        label.font = R.font.sfProTextRegular(size: 20.0)
        return label
    }()
    
    lazy var recordValueLabel: UILabel = {
        let label = UILabel()
        label.textColor = .black
        label.textAlignment = .center
        label.font = R.font.sfProTextRegular(size: 25.0)
        return label
    }()
    
    lazy var restartQuizButton: UIButton = {
        let button = UIButton()
        button.snp.makeConstraints {
            $0.size.equalTo(CGSize(width: 150, height: 50))
        }
        button.setTitle("Restart Quiz", for: .normal)
        button.backgroundColor = .orange
        button.addTarget(self, action: #selector(restartQuiz), for: .touchUpInside)
        return button
    }()
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.hidesBackButton = true
        presenter?.view = self
        presenter?.fetchRecord()
    }
    
    private func setupUI() {
        self.view.addSubview(recordTitleLabel)
        self.view.addSubview(recordValueLabel)
        self.view.addSubview(restartQuizButton)
        recordTitleLabel.snp.makeConstraints {
            $0.top.equalToSuperview().offset(20)
            $0.left.right.equalToSuperview()
        }
        recordValueLabel.snp.makeConstraints {
            $0.top.equalTo(recordTitleLabel.snp.bottom).offset(20)
            $0.left.right.equalToSuperview()
        }
        restartQuizButton.snp.makeConstraints {
            $0.center.equalToSuperview()
        }
    }
    @objc func restartQuiz() {
        self.navigationController?.popViewController(animated: true)
        self.dismiss(animated: true, completion: nil)
        
        let navigationController = UINavigationController(rootViewController: HomeBuilder.build())
        navigationController.navigationBar.isTranslucent = false
        let appDelegate = UIApplication.shared.delegate as? AppDelegate
        
        appDelegate?.window = UIWindow(frame: UIScreen.main.bounds)
        appDelegate?.window?.rootViewController = navigationController
        appDelegate?.window?.makeKeyAndVisible()
    }
    
}

extension FinalViewController: FinalViewProtocol {
    func setRecord(record: Int) {
        recordValueLabel.text = String(record)
        self.setupUI()
    }
}
